
language: java

addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN

script:
  - mvn clean
  - mvn -P chrome,headless,production org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
  - ll -la /home/travis/build/onebeartoe/building-java-applications/web/automation/target/failsafe-reports/
  - cat /home/travis/build/onebeartoe/building-java-applications/web/automation/target/failsafe-reports/*.dump
  - ll -la web/automation/target/screenshots/
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'  
